version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:589485118270:task-definition/sty-aws-sample:12"
        LoadBalancerInfo:
          ContainerName: "aws-sample"
          ContainerPort: 4232
