version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:589485118270:task-definition/stylus-aws-sample:5"
        LoadBalancerInfo:
          ContainerName: "stylus-aws-sample"
          ContainerPort: 80
