version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:589485118270:task-definition/stylus-example-ecs:17"
        LoadBalancerInfo:
          ContainerName: "example-ecs"
          ContainerPort: 4232
