version: 0.2
env:
    git-credential-helper: yes
    # secrets-manager:
    #     DOCKERHUB_USERNAME: 'DockerHubCreds:DOCKERHUB_USERNAME'
    #     DOCKERHUB_PASSWORD: 'DockerHubCreds:DOCKERHUB_PASSWORD'
phases:
    install:
        runtime-versions:
            nodejs: 16
    pre_build:
        commands:
            - REPOSITORY_URI=589485118270.dkr.ecr.us-east-1.amazonaws.com/stylus-sample-nodejs
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
             # - echo Installing dependencies...
            - echo IMAGE_TAG = $IMAGE_TAG
            # - npm install
            - echo Logging in to ECR...
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 589485118270.dkr.ecr.us-east-1.amazonaws.com
            #- echo "DockerHubCreds:xxx" | docker login --username "DockerHubCreds:xxx" --password-stdin 589485118270.dkr.ecr.us-east-1.amazonaws.com
    build:
        commands:
            # - npm run build
            # - echo Build completed on `date`
            - echo Building docker image...
            - docker build -t migration-test-nodeapp:latest -f Dockerfile .
            - docker tag migration-test-nodeapp:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Pushing image to ECR repo...
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo Generating imagedefinitions.json
            - printf '[{"name":"aws-sample","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json
        - appspec.yml
        - taskdef.json
